accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('user/<str:profile_username>/', views.profile, name="profile"),
    path('collaboration/request/<uuid:to_user_id>/', views.send_collaboration_request, name="send_collaboration_request"),
    path('collaboration/respond/<uuid:request_id>/<str:response>', views.manage_collaboration_request, name="manage_collaboration_request"),
    path('collaboration/withdraw/<uuid:request_id>/', views.withdraw_collaboration_request, name="withdraw_collaboration_request"),
    path('user_search', views.user_search, name="user_search"),
    path('collaboration/list/<str:username>', views.collaboration_request_list, name="collaboration_request_list"),
    path('collaborator_list/', views.collaborator_list, name="collaborator_list"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import TemplateView
# from accounts import views as accounts_views
# from papers import views as papers_views
# from research_projects import views as research_project_views
#from . import views

class TopPageView(TemplateView):
    template_name = "index.html"

top_page = TopPageView.as_view()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', top_page, name="top_page"),
    path('accounts/', include('accounts.urls')),
    path('papers/', include('papers.urls')),
    path('research_projects/', include('research_projects.urls'))
    
]

research_projects/urls.py
from django.urls import path

from . import views

app_name = "research_projects"

urlpatterns = [
    path('create_project/', views.create_project, name="create_project"),
    path('detail/<uuid:project_id>/', views.project_detail, name="project_detail"),
    path('add_post/<uuid:project_id>/', views.add_post, name="create_post"),
    path('add_search_paper/<uuid:project_id>/', views.add_search_paper, name="add_search_paper"),
    path('add_paper/<uuid:project_id>/<uuid:paper_id>/', views.add_paper, name="add_paper"),
    path('edit_citation/<uuid:project_id>/<int:index>/', views.edit_citation, name="edit_citation"),
    path('project_list/', views.project_list, name="project_list"),
    path('add_search_member/<uuid:project_id>/', views.add_search_member, name="add_search_member"),
    path('add_member/<uuid:project_id>/<uuid:user_id>/', views.add_member, name="add_member"),
    path('public_switch/<uuid:project_id>/', views.public_switch, name="public_switch"),
    path('visible_switch/<uuid:project_id>/', views.visible_switch, name="visible_switch"),
    path('change_url/<uuid:project_id>/', views.change_url, name="change_url"),
    path('change_description/<uuid:project_id>/', views.change_description, name="change_description"),
    path('delete_project/<uuid:project_id>/', views.delete_project, name="delete_project"),
    path('post_list/<uuid:project_id>/', views.post_list, name="post_list"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid
import base58
# Create your models here.

class CustomUser(AbstractUser):
    user_id = models.UUIDField(verbose_name="user_id", default=uuid.uuid4, editable=False, primary_key=True)
    short_user_id = models.CharField(verbose_name="short_user_id", max_length=8, editable=False, unique=True)
    is_visible = models.BooleanField(verbose_name="is_visible", default=True)

    class Meta:
        db_table = "custom_user"

    def __str__(self):
        return self.username
    
    def save(self, *args, **kwargs):
        if not self.short_user_id:
            self.short_user_id = base58.b58encode(self.user_id.bytes).decode('utf-8')[:8]
        return super().save(*args, **kwargs)

class Collaboration(models.Model):
    request_id = models.UUIDField(verbose_name="request_id", default=uuid.uuid4, primary_key=True)
    from_user = models.ForeignKey(CustomUser, related_name="collaboration_from", on_delete=models.CASCADE)
    to_user = models.ForeignKey(CustomUser, related_name="collaboration_to", on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected")], default="pending")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "collaboration"
        unique_together = ("from_user", "to_user")
    
    def __str__(self):
        return f"{self.from_user} -> {self.to_user} ({self.status})"
    

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

# class LoginForm(forms.Form):
#     username = forms.CharField(label="username", max_length=255)
#     password = forms.CharField(label="password", widget=forms.PasswordInput(attrs={"placeholder": "password"}))

class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "email", "password")
        widgets = {"password": forms.PasswordInput(attrs={"palaceholder": "password"})}
    
    password2 = forms.CharField(label="confirmation password", required=True, widget=forms.PasswordInput(attrs={"placeholder": "again"}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs = {"placeholder": "username"}
        self.fields["email"].required = True
        self.fields["email"].widget.attrs = {"placeholder": "email"}


class UserSearchForm(forms.Form):
    query = forms.CharField(max_length=100, required=False, label='query')


class ManageCollaborationRequestForm(forms.Form):
    CHOICES = [("accept", "Accept"), ("reject", "Reject")]
    choice = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect, label="応答")

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http.response import HttpResponseRedirect
from django.template.response import TemplateResponse
from django.http import JsonResponse
from django.views import View
from django.views.generic import ListView
from django.contrib.auth import login, authenticate
from django.urls import reverse, reverse_lazy
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from django.views.generic import TemplateView, DetailView, CreateView, DeleteView
from django.contrib.auth import views as auth_views

from django.db.models import Q

from .forms import RegisterForm, UserSearchForm, ManageCollaborationRequestForm
import base58
from .models import CustomUser, Collaboration

# Create your views here.


class IndexView(TemplateView):
    template_name = "accounts/index.html"
    
index = IndexView.as_view()


class LoginView(auth_views.LoginView):
#    form_class = LoginForm
#デフォルトのAuthenticationFormを呼んでいる
    template_name = "accounts/login.html"
    redirect_authenticated_user = True

    def get_success_url(self):
        username = self.request.user.username
        #ここでの"profile"はurl_patternsのnameに対応してる
        return reverse_lazy("accounts:profile", kwargs={"profile_username": username})
    
login = LoginView.as_view()


class LogoutView(auth_views.LogoutView):
    next_page = "accounts:login"

logout = LogoutView.as_view()


class RegisterView(CreateView):
    model = CustomUser
    template_name = 'accounts/register.html'
    form_class = RegisterForm

    def get_success_url(self):
        return reverse_lazy("accounts:profile", kwargs={"profile_username": self.object.username})
    
    def form_valid(self, form):
        user = form.save(commit=False)
        
        # パスワードをハッシュ化して保存
        user.set_password(form.cleaned_data["password"])  # ハッシュ化
        user.save()  # ユーザーをデータベースに保存

        # 認証後にログイン
        auth_user = authenticate(username=form.cleaned_data["username"], password=form.cleaned_data["password"])
        login(self.request, auth_user)
        return super().form_valid(form)

register = RegisterView.as_view()


class ProfileView(DetailView):
    model = CustomUser
    template_name = 'accounts/profile.html'
    context_object_name = 'user'

    def get_object(self):
        """ユーザー名に基づいてプロフィールを取得"""
        username = self.kwargs.get('profile_username')
        user = get_object_or_404(CustomUser, username=username)
        return user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ログインユーザーが自分のプロフィールページを表示しているか判定
        #self.objectはget_objectを通じて決定されます
        context['is_self'] = (self.request.user == self.object)
        context['user'] = self.request.user
        context['profile_user'] = self.object    
        context['profile_user_projects'] = self.object.projects.all()
        collaborators = Collaboration.objects.filter((Q(from_user=self.request.user) | Q(to_user=self.request.user)), status="accepted").values_list("from_user", "to_user")
        context['collaborator_list'] = [user   for pair in collaborators    for user in pair    if user != self.request.user.user_id]
        to_pending_collaborators = Collaboration.objects.filter(from_user=self.request.user, status="pending").values_list("to_user", flat=True)
        context['to_pending_collaborator_list'] = to_pending_collaborators
        from_pending_collaborators = Collaboration.objects.filter(to_user=self.request.user, status="pending").values_list("from_user", flat=True)
        context['from_pending_collaborator_list'] = from_pending_collaborators
        context['numbers'] = [1, 2, 3, 4] 
        if context["is_self"]:
            paginator = Paginator(self.object.projects.all().order_by("-updated_at"), 20)
        else:
            paginator = Paginator(self.object.projects.filter(Q(is_public=True) | Q(members=self.request.user)).order_by("-updated_at"), 20)

        page = self.request.GET.get("page")
        try:
            page_obj = paginator.page(page)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)
        context["page_obj"] = page_obj
        return context
    
profile = ProfileView.as_view()


class SendCollaborationRequestView(View):
    def post(self, request, *args, **kwargs):
        to_user = get_object_or_404(CustomUser, user_id=kwargs["to_user_id"])

        collaboration, created = Collaboration.objects.get_or_create(from_user=request.user , to_user=to_user)
        if created:
            return JsonResponse({"message": "既に送信されています"})
        else:
            return JsonResponse({"message": "送信されました"})

send_collaboration_request = SendCollaborationRequestView.as_view()


class WithdrawCollaborationRequestView(View):
    def post(self, request, *args, **kwargs):
        collaboration_request = get_object_or_404(Collaboration, request_id=kwargs.get("request_id"))

        collaboration_request.delete()
        return JsonResponse({"message": "Withdrawed request"})

withdraw_collaboration_request = WithdrawCollaborationRequestView.as_view()


class ManageCollaborationRequestView(View):
    def post(self, request, *args, **kwargs):
        collaboration_request = get_object_or_404(Collaboration, request_id=kwargs.get("request_id"))
        
        if kwargs.get("response") == "accept":
            collaboration_request.status = "accepted"
            collaboration_request.save()
            return JsonResponse({"message": "request accepted"})
        
        elif kwargs.get("response") == "reject":
            collaboration_request.delete()
            return JsonResponse({"message": "request rejected"})
        
        else:
            return JsonResponse({"message": "invalid response"})
        
manage_collaboration_request = ManageCollaborationRequestView.as_view()

            
class UserSearchView(ListView):
    template_name = "accounts/user_search.html"
    context_object_name = "users"
    paginate_by = 20
    form_class = UserSearchForm

    def get_queryset(self):
        form = UserSearchForm(self.request.GET)

        if form.is_valid():
            query = form.cleaned_data.get("query")
            if query:
                queryset = CustomUser.objects.filter(short_user_id=query)
            else:
                queryset = CustomUser.objects.all().order_by("username")

        else:
            queryset = CustomUser.objects.all()
        
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #ページネーションのために使う
        context['numbers'] = [1, 2, 3, 4]  # 配列をコンテキストに追加
        context["form"] = UserSearchForm(self.request.GET or None)
        return context

user_search = UserSearchView.as_view()


class CollaborationRequestListView(ListView):
    template_name="accounts/collaboration_request_list.html"
    context_object_name = "collaboration_requests"
    paginate_by = 20

    def get_queryset(self):
        return Collaboration.objects.filter(to_user=self.request.user,status="pending").order_by("created_at")

collaboration_request_list = CollaborationRequestListView.as_view()


class CollaboratorListView(ListView):
    template_name = "accounts/collaborator_list.html"
    context_object_name = "collaborators"
    paginate_by = 20

    def get_queryset(self):
        collaborators_temp = Collaboration.objects.filter(Q(from_user=self.request.user, status="accepted") | Q(to_user=self.request.user, status="accepted")).values_list("from_user", "to_user")
        collaborators =[user_id  for pair in collaborators_temp  for user_id in pair  if user_id != self.request.user.user_id]
        queryset = CustomUser.objects.filter(user_id__in = collaborators)
        return queryset
    
collaborator_list = CollaboratorListView.as_view()

templates/accounts/collaboration_request_list.html
{% extends "base.html" %}
{% load static %}


{# -- タイトル -- #}
{% block title%}公開プロジェクト一覧{% endblock %}

{# -- CSS -- #}
{% block extra_css %}
    <link href={% static 'css/accounts/collaboration_request_list.css' %} rel="stylesheet" media="all">
{% endblock %}

{# --メインコンテンツ --#}
{% block main %}
    <div class="titleb"><h2>共同研究申請リスト</h2>
    </div>

    <div id="request_list">
        {% if collaboration_requests %}
        {% for collaboration_request in collaboration_requests %}
        <div class="request">
            {{ collaboration_request.from_user.username }}
            <form method="post" action="{% url 'accounts:manage_collaboration_request' request_id=collaboration_request.request_id response="accept" %}">
                {% csrf_token %}
                <button type="submit">accept</button>
            </form>
            <form method="post" action="{% url 'accounts:manage_collaboration_request' request_id=collaboration_request.request_id response="reject" %}">
                {% csrf_token %}
                <button type="submit">reject</button>
            </form>
        </div>
        {% endfor %}
        {% else %}
        <div class="request">
            リクエストがありません
        </div>
        {% endif %}

        <div id="pagination">
            {% if page_obj.paginator.num_pages < 10 %}

            {% for i in page_obj.paginator.page_range %}
            <div class="page_num">
                {% if i == page_obj.number %}
                <span class="current_page">{{ i }}</span>
                {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            </div>
            {% endfor %}

            {% elif page_obj.number < 4 %}
            {% for i in numbers %}
            <div class="page_num">
                {% if page_obj.number == i %}
                <span class="current_page">{{ i }}</span>
                {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            </div>
            {% endfor %}
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages|add:"-1" }}">{{ page_obj.paginator.num_pages|add:"-1" }}</a></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></div>
            
            {% elif page_obj.number > page_obj.paginator.num_pages|add:"-3" %}
            <div class="page_num"><a href="?page=1">1</a></div>
            <div class="page_num"><a href="?page=2">2</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            {% for i in numbers %}
            <div class="page_num">
                {% with page_obj.paginator.num_pages|add:-5|add:i as calculated_page %}
                {% if calculated_page == page_obj.number %}
                <span class="current_page">{{ page_obj.paginator.num_pages|add:-5 |add:i }}</span>
                {% else %}
                <a href="?page={{ page_obj.paginator.num_pages|add:-5 |add:i }}">{{ page_obj.paginator.num_pages|add:"-5" |add:i }}</a>
                {% endif %}
                {% endwith %}
            </div>
            {% endfor %}

            {% else %}
            <div class="page_num"><a href="?page=1">1</a></div>
            <div class="page_num"><a href="?page=2">2</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></div>
            <div class="page_num"><span class="current_page">{{ page_obj.number }}</span></div>
            <div class="page_num"><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages|add:"-1" }}">{{ page_obj.paginator.num_pages|add:"-1" }}</a></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages}}">{{ page_obj.paginator.num_pages }}</a></div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/accounts/index.html
{% extends "base.html" %}
{% load static %}

{# -- タイトル -- #}
{% block title%}アカウントトップ{% endblock %}

{# -- CSS -- #}
{% block extra_css %}
    <style type="text/css">
        main > section > .mx-auto {
            max-width: 400px;
        }
    </style>
{% endblock %}

{# --メインコンテンツ --#}
{% block main %}
    <main>
        {{ user.name }}
        <div class="mt-3">
            <a href="{% url 'accounts:login' %}" class="btn btn-secondary">Login</a>
        </div>
    </main>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{# -- タイトル -- #}
{% block title%}ログイン{% endblock %}

{# -- CSS -- #}
{% block extra_css %}
    <style type="text/css">
        main > section > .mx-auto {
            max-width: 400px;
        }
    </style>
{% endblock %}

{# --メインコンテンツ --#}
{% block main %}
    <main>
        {{ user }}
        <form method="post">
            <section id="login_form" class="container mb-4">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {% for field in form %}
                {{ field.label }}
                {{ field }}
                {{ field.errors }}
                <br>
                {% endfor %}
            </section>
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Login</button>
                <a href="{% url 'accounts:index' %}" class="btn btn-secondary">Back</a>
                <a href="{% url 'accounts:register' %}" class="btn btn-secondary">新規登録</a>
            </div>
        </form>
    </main>
{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}

{# -- タイトル -- #}
{% block title%}profile{% endblock %}

{# -- CSS -- #}
{% block extra_css %}
    <link href={% static 'css/accounts/profile.css' %} rel="stylesheet" media="all">
{% endblock %}

{# --メインコンテンツ --#}
{% block main %}
    <main>
        <div class="titleb">
        {{ profile_user }}のページ
        </div>
        {% if is_self %}
        <div id="management">
        <a href="{% url 'accounts:collaboration_request_list' username=user.username %}">共同研究申請処理</a><br>
        <a href="{% url 'research_projects:create_project' %}">プロジェクト作成</a>
        <form method="post" class="btn btn-secondary" action="{% url 'accounts:logout' %}">
            {% csrf_token %}
            <button type="submit">ログアウト</button>
        </form>
        </div>

        {% else %}

        <div id="management">
        {% if profile_user.user_id in collaborator_list %}
        <span class="done">既に共同研究者です</span>
        {% elif profile_user.user_id in from_pending_collaborator_list %}
        <a href="{% url 'accounts:manage_collaboration_request' username=user.username %}">リクエストに応答</a>
        {% elif profile_user.user_id in to_pending_collaborator_list %}
        <span class="done">現在申請中</span>
        {% else %}
        <form method="post" class="request" action="{% url 'accounts:send_collaboration_request' to_user_id=profile_user.user_id %}">
            {% csrf_token %}
            <button type="submit">共同研究申請</button>
        </form>
        {% endif %}
        </div>
        {% endif %}


        <div class="titlef">
            参加プロジェクト一覧
        </div>
        <div id="project_list">

        {% for project in page_obj %}
        <div class="project">
        {% if project.is_public or user in project.members.all %}
        <a href="{% url 'research_projects:project_detail' project.project_id %}">
            {{ project.name }}  short id:{{ project.short_project_id }} <br>
            {{ project.description }}
        </a>
        {% else %}
        {{ project.name }} {{ project.short_project_id }} {{ project.description }}
        {% endif %}
        </div>

        {% endfor %}

        <div id="pagination">
            {% if page_obj.paginator.num_pages < 10 %}

            {% for i in page_obj.paginator.page_range %}
            <div class="page_num">
                {% if i == page_obj.number %}
                <span class="current_page">{{ i }}</span>
                {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            </div>
            {% endfor %}

            {% elif page_obj.number < 4 %}
            {% for i in numbers %}
            <div class="page_num">
                {% if page_obj.number == i %}
                <span class="current_page">{{ i }}</span>
                {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            </div>
            {% endfor %}
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages|add:"-1" }}">{{ page_obj.paginator.num_pages|add:"-1" }}</a></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></div>
            
            {% elif page_obj.number > page_obj.paginator.num_pages|add:"-3" %}
            <div class="page_num"><a href="?page=1">1</a></div>
            <div class="page_num"><a href="?page=2">2</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            {% for i in numbers %}
            <div class="page_num">
                {% with page_obj.paginator.num_pages|add:-5|add:i as calculated_page %}
                {% if calculated_page == page_obj.number %}
                <span class="current_page">{{ page_obj.paginator.num_pages|add:-5 |add:i }}</span>
                {% else %}
                <a href="?page={{ page_obj.paginator.num_pages|add:-5 |add:i }}">{{ page_obj.paginator.num_pages|add:"-5" |add:i }}</a>
                {% endif %}
                {% endwith %}
            </div>
            {% endfor %}

            {% else %}
            <div class="page_num"><a href="?page=1">1</a></div>
            <div class="page_num"><a href="?page=2">2</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></div>
            <div class="page_num"><span class="current_page">{{ page_obj.number }}</span></div>
            <div class="page_num"><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages|add:"-1" }}">{{ page_obj.paginator.num_pages|add:"-1" }}</a></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages}}">{{ page_obj.paginator.num_pages }}</a></div>
            {% endif %}
        </div>
        </div>
    </main>
{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}
{% load static %}

{# -- タイトル -- #}
{% block title%}会員登録{% endblock %}

{# --メインコンテンツ --#}
{% block main %}
    <main>
        {{ user }}
        <form method="post">
            <section id="register_form" class="container mb-4">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {% for field in form %}
                {{ field.label }}
                {{ field }}
                {{ field.errors }}
                <br>
                {% endfor %}
            </section>
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Create</button>
                <a href="{% url 'accounts:index' %}" class="btn btn-secondary">Back</a>
            </div>
        </form>
    </main>
{% endblock %}

templates/accounts/user_search.html
{% extends "base.html" %}
{% load static %}


{# -- タイトル -- #}
{% block title%}公開プロジェクト一覧{% endblock %}

{# -- CSS -- #}
{% block extra_css %}
    <link href={% static 'css/research_projects/project_list.css' %} rel="stylesheet" media="all">
{% endblock %}

{# --メインコンテンツ --#}
{% block main %}
<div class="titleb"><h2>ユーザー検索</h2>
    </div>
    <div id="search">
        <form method="GET" action="{% url "accounts:user_search" %}">
            <p class="query">
            {{ form.query }}
            </p>
            <button type="submit">検索</button>
        </form>
    </div>

    <div class="titlef">
        検索結果
    </div>
    <div id="project_list">
        {% if users %}
        {% for user in users %}
        <div class="user">
            <a href="{% url 'accounts:profile' profile_username=user.username %}">{{ user.username }}</a>
        </div>
        {% endfor %}
        {% else %}
        <div class="project">
            ユーザーが見つかりません
        </div>
        {% endif %}

        <div id="pagination">
            {% if page_obj.paginator.num_pages < 10 %}

            {% for i in page_obj.paginator.page_range %}
            <div class="page_num">
                {% if i == page_obj.number %}
                <span class="current_page">{{ i }}</span>
                {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            </div>
            {% endfor %}

            {% elif page_obj.number < 4 %}
            {% for i in numbers %}
            <div class="page_num">
                {% if page_obj.number == i %}
                <span class="current_page">{{ i }}</span>
                {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            </div>
            {% endfor %}
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages|add:"-1" }}">{{ page_obj.paginator.num_pages|add:"-1" }}</a></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></div>
            
            {% elif page_obj.number > page_obj.paginator.num_pages|add:"-3" %}
            <div class="page_num"><a href="?page=1">1</a></div>
            <div class="page_num"><a href="?page=2">2</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            {% for i in numbers %}
            <div class="page_num">
                {% with page_obj.paginator.num_pages|add:-5|add:i as calculated_page %}
                {% if calculated_page == page_obj.number %}
                <span class="current_page">{{ page_obj.paginator.num_pages|add:-5 |add:i }}</span>
                {% else %}
                <a href="?page={{ page_obj.paginator.num_pages|add:-5 |add:i }}">{{ page_obj.paginator.num_pages|add:"-5" |add:i }}</a>
                {% endif %}
                {% endwith %}
            </div>
            {% endfor %}

            {% else %}
            <div class="page_num"><a href="?page=1">1</a></div>
            <div class="page_num"><a href="?page=2">2</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></div>
            <div class="page_num"><span class="current_page">{{ page_obj.number }}</span></div>
            <div class="page_num"><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages|add:"-1" }}">{{ page_obj.paginator.num_pages|add:"-1" }}</a></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages}}">{{ page_obj.paginator.num_pages }}</a></div>
            {% endif %}
        </div>
    </div>
{% endblock %}