accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('user/<str:profile_username>/', views.profile, name="profile"),
    path('collaboration/request/<uuid:to_user_id>/', views.send_collaboration_request, name="send_collaboration_request"),
    path('collaboration/respond/<uuid:request_id>/<str:response>', views.manage_collaboration_request, name="manage_collaboration_request"),
    path('collaboration/withdraw/<uuid:request_id>/', views.withdraw_collaboration_request, name="withdraw_collaboration_request"),
    path('user_search', views.user_search, name="user_search"),
    path('collaboration/list/<str:username>', views.collaboration_request_list, name="collaboration_request_list"),
    path('collaborator_list/', views.collaborator_list, name="collaborator_list"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import TemplateView
# from accounts import views as accounts_views
# from papers import views as papers_views
# from research_projects import views as research_project_views
#from . import views

class TopPageView(TemplateView):
    template_name = "index.html"

top_page = TopPageView.as_view()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', top_page, name="top_page"),
    path('accounts/', include('accounts.urls')),
    path('papers/', include('papers.urls')),
    path('research_projects/', include('research_projects.urls'))
    
]

papers/urls.py
from django.urls import path

from . import views

app_name = "papers"

urlpatterns = [
    path('import_paper', views.import_paper, name="import_paper"),
    path('paper_list', views.paper_list, name="paper_list"),
    path('paper_detail/<uuid:paper_id>', views.paper_detail, name="paper_detail"),
#    path('detail/<uuid:pk>', views.project_detail, name="project_detail"),
#    path('add_post/<uuid:project_id>', views.create_post, name="create_post")
]

papers/models.py
from django.db import models
import uuid
from accounts.models import CustomUser
# Create your models here.

#publisher class
class Publisher(models.Model):
    class Meta:
        db_table = "publisher"
    
    name = models.TextField(verbose_name="publisher name", unique=True)

    def __str__(self):
        return self.name
    
#university class
class University(models.Model):
    class Meta:
        db_table = "university"

    name = models.TextField(verbose_name="name", max_length=255)

    def __str__(self):
        return self.name

#author class
class Author(models.Model):
    class Meta:
        db_table = "author"
    
    first_name = models.TextField(verbose_name="first_name", max_length=255)
    last_name = models.TextField(verbose_name="last_name", max_length=255)
    affiliation = models.ManyToManyField(University, verbose_name="affiliation", blank=True, null=True)

    def __str__(self):
        return self.last_name


#paper class
class Paper(models.Model):
    class Mata:
        db_table = "paper"

    paper_id = models.UUIDField(verbose_name="paper_id", primary_key=True, default=uuid.uuid4)
    title = models.TextField(verbose_name="title")
    publisher = models.ForeignKey(Publisher, verbose_name="publisher", blank=True, null=True, on_delete=models.PROTECT)
    authors = models.ManyToManyField(Author, verbose_name="author")
    arxiv = models.TextField(verbose_name="arxiv_id", blank=True, null=True, unique=True)
    doi = models.TextField(verbose_name="doi", blank=True, null=True, unique=True)
    published_date = models.DateField(verbose_name="published_date")
    bookmark_user = models.ManyToManyField(CustomUser, verbose_name="bookmark_user", related_name="bookmark_paper")

    def __str__(self):
        return self.title
    
    def clean(self):
        # 空文字列に対して一意性を無視する
        if self.arxiv == "":
            self.arxiv = None  # 空文字列を None に変換して一意性制約を回避
        
        if self.doi == "":
            self.doi = None
        
        super().clean()
    

papers/forms.py
from django import forms
from .models import Paper

class ImportPaperForm(forms.ModelForm):
    switch = forms.ChoiceField(choices=[("arxiv", "arxiv"), ("DOI", "DOI")], required=True, widget=forms.RadioSelect)
    
    class Meta:
        model = Paper
        fields = ['arxiv', 'doi']

class SearchPaperForm(forms.Form):
    query = forms.CharField(max_length=100, required=False, label='keyword')

papers/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import CreateView, ListView, DetailView
from .forms import ImportPaperForm, SearchPaperForm
from .models import Paper, Author
from django.urls import reverse_lazy
from datetime import datetime
from django.db.models import Q

import requests
import xml.etree.ElementTree as ET

#from crossref.restful import Works
CROSSREF_API_URL = "https://api.crossref.org/works"

#import arxiv
ARXIV_API_URL = "http://export.arxiv.org/api/query"

# Create your views here.

class ImportPaperView(CreateView):
    model = Paper
    form_class = ImportPaperForm
    template_name = "papers/import_paper.html"

    def get_success_url(self):
        if self.kwargs.get("project_id"):
            return reverse_lazy("research_projects:add_search_paper", project_id=self.kwargs.get())
        else:
            return reverse_lazy("papers:paper_list")

    def form_valid(self, form):
        if form.cleaned_data.get('switch') == "arxiv":
            paper = form.save(commit=False)
            arxiv_id = paper.arxiv
            params = {
                'search_query': arxiv_id,  # 特定の論文をarxiv IDで検索
                'max_results': 1,                  # 最大結果件数を1件に設定
            }
            response = requests.get(ARXIV_API_URL, params)
            if response.status_code == 200:
                root = ET.fromstring(response.text)
                entries = root.findall('{http://www.w3.org/2005/Atom}entry')

                if entries:
                    for entry in entries:
                        paper.title = entry.find('{http://www.w3.org/2005/Atom}title').text
                        authors = []
                        for author in entry.findall('{http://www.w3.org/2005/Atom}author'):
                            name = author.find('{http://www.w3.org/2005/Atom}name')
                            if name is not None:
                                # すでに存在する著者を取得、なければ新規作成
                                first_name = " ".join(name.text.split(" ")[:-1])
                                last_name = name.text.split(" ")[-1]
                                author_instance, created = Author.objects.get_or_create(first_name=first_name, last_name=last_name)
                                authors.append(author_instance)
                        published_str = entry.find('{http://www.w3.org/2005/Atom}published').text
                        paper.published_date = datetime.fromisoformat(published_str[:-1]).date()
            paper.save()
            paper.authors.set(authors) 
            return super().form_valid(form)
        
        elif form.cleaned_data.get('switch') == "DOI":
            paper = form.save(commit=False)
            doi = paper.doi
            request_url = f"{CROSSREF_API_URL}/{doi}"
            response = requests.get(request_url)
            if response.status_code == 200:
                data = response.json()
                message = data["message"]
                paper.title = message["title"][0]
                authors = []
                for author in message["author"]:
                    first_name = f"{author['given']}"
                    last_name = f"{author['family']}"
                    author_instance, created = Author.objects.get_or_create(first_name=first_name, last_name=last_name)
                    authors.append(author_instance)
        
                arxiv_id = None
                links = message.get("link", [])
                for link in links:
                    if "arxiv" in link["URL"]:
                        arxiv_id = link["URL"].split("/")[-1]
                        break
                paper.arxiv = arxiv_id
                published_parts = message["published"]["date-parts"][0]
                ymd = [1,1,1]
                for i in range(len(published_parts)):
                    ymd[i] = published_parts[i]
                paper.published_date = datetime(ymd[0], ymd[1], ymd[2]).date()

            paper.save()
            paper.authors.set(authors)
            return super().form_valid(form)

import_paper = ImportPaperView.as_view()


class PaperDetailView(DetailView):
    model = Paper
    template_name = "papers/paper_detail.html"
    context_object_name = "paper"

    def get_object(self, queryset=None):
        # URLからproject_idを取得して、それを元にProjectオブジェクトを取得
        paper_id = self.kwargs.get('paper_id')
        return get_object_or_404(Paper, paper_id=paper_id)

paper_detail = PaperDetailView.as_view()


class PaperListView(ListView):
    template_name = "papers/paper_list.html"
    context_object_name = "papers"
    paginate_by = 20

    def get_queryset(self):
        form = SearchPaperForm(self.request.GET)
        queryset = Paper.objects.all()
        if "query" in self.request.GET:
            if form.is_valid():
                query = form.cleaned_data.get("query")
                if query:
                    queryset = queryset.filter(Q(title__icontains=query) | Q(arxiv__icontains=query) | Q(doi__icontains=query))
        else:
            queryset = Paper.objects.all()
        
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #ページネーションのために使う
        context['numbers'] = [1, 2, 3, 4]  # 配列をコンテキストに追加

        context["form"] = SearchPaperForm(self.request.GET or None)
        if "query" in self.request.GET:
            query = self.request.GET.get("query", "").strip()
            if query:
                context["message"] = f"検索結果： {query}"
            else:
                context["message"] = "全ての結果" 
        else:
            context["message"] = "全ての結果"
        return context

paper_list = PaperListView.as_view()

templates/papers/import_paper.html
{% extends "base.html" %}
{% load static %}

{# -- タイトル -- #}
{% block title%}import paper{% endblock %}

{# -- CSS -- #}
{% block extra_css %}
    <style type="text/css">
        main > section > .mx-auto {
            max-width: 400px;
        }
    </style>
{% endblock %}

{# --メインコンテンツ --#}
{% block main %}
    <main>
        {{ user }}
        <form method="post">
            <section id="import_paper_form" class="container mb-4">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {% for field in form %}
                {{ field.label }}
                {{ field }}
                {{ field.errors }}
                <br>
                {% endfor %}
            </section>
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Create</button>
                <a href="{% url 'accounts:index' %}" class="btn btn-secondary">Back</a>
            </div>
        </form>
    </main>
{% endblock %}

templates/papers/paper_detail.html
{% extends "base.html" %}
{% load static %}

{# -- タイトル -- #}
{% block title %}Paper Detail: {{ paper.title }}{% endblock %}

{# -- CSS -- #}
{% block extra_css %}
{% endblock %}

{# --メインコンテンツ --#}
{% block main %}
    <h1>{{ paper.title }}<br></h1>
    <a href="{% url 'accounts:index' %}" class="btn btn-secondary">Back</a>
{% endblock %}

templates/papers/paper_list.html
{% extends "base.html" %}
{% load static %}


{# -- タイトル -- #}
{% block title%}公開プロジェクト一覧{% endblock %}

{# -- CSS -- #}
{% block extra_css %}
    <link href={% static 'css/papers/paper_list.css' %} rel="stylesheet" media="all">
    </style>
    
{% endblock %}

{# --メインコンテンツ --#}
{% block main %}
    <div class="titleb"><h2>文献一覧</h2>
    </div>
    <div id="paper_list">
        <a href="{% url 'papers:import_paper' %}">+ import paper</a>
        {% if papers %}
        {% for paper in papers %}
        <div class="paper">
            <a href="{% url 'papers:paper_detail' paper_id=paper.paper_id %}">{{ paper.title }}</a>
        </div>
        {% endfor %}
        {% else %}
        <div class="project">
            文献がありません
        </div>
        {% endif %}

        <div id="pagination">
            {% if page_obj.paginator.num_pages < 10 %}

            {% for i in page_obj.paginator.page_range %}
            <div class="page_num">
                {% if i == page_obj.number %}
                <span class="current_page">{{ i }}</span>
                {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            </div>
            {% endfor %}

            {% elif page_obj.number < 4 %}
            {% for i in numbers %}
            <div class="page_num">
                {% if page_obj.number == i %}
                <span class="current_page">{{ i }}</span>
                {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            </div>
            {% endfor %}
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages|add:"-1" }}">{{ page_obj.paginator.num_pages|add:"-1" }}</a></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></div>
            
            {% elif page_obj.number > page_obj.paginator.num_pages|add:"-3" %}
            <div class="page_num"><a href="?page=1">1</a></div>
            <div class="page_num"><a href="?page=2">2</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            {% for i in numbers %}
            <div class="page_num">
                {% with page_obj.paginator.num_pages|add:-5|add:i as calculated_page %}
                {% if calculated_page == page_obj.number %}
                <span class="current_page">{{ page_obj.paginator.num_pages|add:-5 |add:i }}</span>
                {% else %}
                <a href="?page={{ page_obj.paginator.num_pages|add:-5 |add:i }}">{{ page_obj.paginator.num_pages|add:"-5" |add:i }}</a>
                {% endif %}
                {% endwith %}
            </div>
            {% endfor %}

            {% else %}
            <div class="page_num"><a href="?page=1">1</a></div>
            <div class="page_num"><a href="?page=2">2</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></div>
            <div class="page_num"><span class="current_page">{{ page_obj.number }}</span></div>
            <div class="page_num"><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages|add:"-1" }}">{{ page_obj.paginator.num_pages|add:"-1" }}</a></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages}}">{{ page_obj.paginator.num_pages }}</a></div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{# -- フッターは表示しない -- #}
{% block footer %}
{% endblock %}