accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('user/<str:profile_username>/', views.profile, name="profile"),
    path('collaboration/request/<uuid:to_user_id>/', views.send_collaboration_request, name="send_collaboration_request"),
    path('collaboration/respond/<uuid:request_id>/<str:response>', views.manage_collaboration_request, name="manage_collaboration_request"),
    path('collaboration/withdraw/<uuid:request_id>/', views.withdraw_collaboration_request, name="withdraw_collaboration_request"),
    path('user_search', views.user_search, name="user_search"),
    path('collaboration/list/<str:username>', views.collaboration_request_list, name="collaboration_request_list"),
    path('collaborator_list/', views.collaborator_list, name="collaborator_list"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import TemplateView
# from accounts import views as accounts_views
# from papers import views as papers_views
# from research_projects import views as research_project_views
#from . import views

class TopPageView(TemplateView):
    template_name = "index.html"

top_page = TopPageView.as_view()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', top_page, name="top_page"),
    path('accounts/', include('accounts.urls')),
    path('papers/', include('papers.urls')),
    path('research_projects/', include('research_projects.urls'))
    
]

papers/urls.py
from django.urls import path

from . import views

app_name = "papers"

urlpatterns = [
    path('import_paper', views.import_paper, name="import_paper"),
    path('paper_list', views.paper_list, name="paper_list"),
    path('paper_detail/<uuid:paper_id>', views.paper_detail, name="paper_detail"),
#    path('detail/<uuid:pk>', views.project_detail, name="project_detail"),
#    path('add_post/<uuid:project_id>', views.create_post, name="create_post")
]

research_projects/urls.py
from django.urls import path

from . import views

app_name = "research_projects"

urlpatterns = [
    path('create_project/', views.create_project, name="create_project"),
    path('detail/<uuid:project_id>/', views.project_detail, name="project_detail"),
    path('add_post/<uuid:project_id>/', views.add_post, name="create_post"),
    path('add_search_paper/<uuid:project_id>/', views.add_search_paper, name="add_search_paper"),
    path('add_paper/<uuid:project_id>/<uuid:paper_id>/', views.add_paper, name="add_paper"),
    path('edit_citation/<uuid:project_id>/<int:index>/', views.edit_citation, name="edit_citation"),
    path('project_list/', views.project_list, name="project_list"),
    path('add_search_member/<uuid:project_id>/', views.add_search_member, name="add_search_member"),
    path('add_member/<uuid:project_id>/<uuid:user_id>/', views.add_member, name="add_member"),
    path('public_switch/<uuid:project_id>/', views.public_switch, name="public_switch"),
    path('visible_switch/<uuid:project_id>/', views.visible_switch, name="visible_switch"),
    path('change_url/<uuid:project_id>/', views.change_url, name="change_url"),
    path('change_description/<uuid:project_id>/', views.change_description, name="change_description"),
    path('delete_project/<uuid:project_id>/', views.delete_project, name="delete_project"),
    path('post_list/<uuid:project_id>/', views.post_list, name="post_list"),
]

research_projects/forms.py
from django import forms
from django.db.models import Q
from django.contrib.auth import get_user_model
from .models import Project, PapersIndices
from accounts.models import Collaboration


# class CreateProjectForm(forms.ModelForm):
#     class Meta:
#         model = Project

# class AddPaperForm(forms.ModelForm):
#     class Meta:
#         model = PapersIndices
#         fields = ["paper",]
#         widgets = {"paper": autocomplete.ModelSelect2(url="research_projects:paper-autocomplete"),}

class AddMemberForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["members"]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        project = kwargs.pop("project")
        super().__init__(*args, **kwargs)

        if user:
            collaborators = Collaboration.objects.filter((Q(from_user=user) | Q(to_user=user)), status="accepted").values_list("from_user", "to_user")
            accepted_users = [user_id   for pair in collaborators    for user_id in pair    if user_id != user.user_id]
            existing_members = project.members.all().values_list("user_id", flat=True)
            self.fields["members"].queryset = get_user_model().objects.filter(user_id__in=accepted_users).exclude(user_id__in=existing_members)


class SearchMemberForm(forms.Form):
    query = forms.CharField(max_length=100, required=False, label="keyword")

class SearchPaperForm(forms.Form):
    query = forms.CharField(max_length=100, required=False, label='keyword')

class SearchProjectForm(forms.Form):
    query = forms.CharField(max_length=100, required=False, label='keyword')

research_projects/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView, DetailView, UpdateView, ListView, FormView, DeleteView
from django.db.models import Max
from django.db import transaction
from django.http import JsonResponse
from django.views import View
from accounts.models import CustomUser, Collaboration
from .models import Project, Post, PapersIndices
from .forms import AddMemberForm, SearchMemberForm, SearchProjectForm, SearchPaperForm
from papers.models import Paper
from django.urls import reverse_lazy
from django.db.models import Q


# Create your views here.

class CreateProjectView(CreateView):
    model = Project
    template_name = "research_projects/create_project.html"
    fields = ["name", "description", "project_url"]
    
    def get_success_url(self):
        # success_url を動的に取得して返す
        return reverse_lazy('research_projects:project_detail', kwargs={'project_id': self.object.project_id})
    
    def form_valid(self, form):
        project = form.save(commit=False)
        project.save()
        
        project.members.add(self.request.user)

        return super().form_valid(form)
    
create_project = CreateProjectView.as_view()


class ProjectDetailView(DetailView):
    model = Project
    template_name = "research_projects/project_detail.html"
    context_object_name = "project"

    def get_object(self, queryset=None):
        # URLからproject_idを取得して、それを元にProjectオブジェクトを取得
        project_id = self.kwargs.get('project_id')
        return get_object_or_404(Project, project_id=project_id)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["members_short_list"] = self.object.members.all()[:5]
        context["posts_short_list"] = self.object.posts.all().order_by("-posted_on")[:5]
        return context

project_detail = ProjectDetailView.as_view()


class AddSearchMemberView(ListView):
    model = CustomUser
    template_name = "research_projects/add_search_member.html"
    context_object_name = "collaborators"
    paginate_by = 20

    def get_queryset(self):
        form = SearchMemberForm(self.request.GET)

        if form.is_valid():
            query = form.cleaned_data.get("query")    
            collaborators_temp = Collaboration.objects.filter(Q(from_user=self.request.user, status="accepted") | Q(to_user=self.request.user, status="accepted")).values_list("from_user", "to_user")
            collaborators =[user_id  for pair in collaborators_temp  for user_id in pair  if user_id != self.request.user.user_id]
            queryset = CustomUser.objects.filter(user_id__in = collaborators)
            
            if query:
                queryset = queryset.filter(Q(username__icontains=query) | Q(user_id__icontains=query) | Q(short_user_id__icontains=query))
                return queryset
            else:
                return queryset
            
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["project_id"] = self.kwargs.get("project_id")
        #ページネーションのために使う
        context['numbers'] = [1, 2, 3, 4]
        return context

add_search_member = AddSearchMemberView.as_view()


class AddMemberView(View):
    def post(self, request, *args, **kwargs):
        project_id = kwargs.get("project_id")
        project = get_object_or_404(Project, project_id=project_id)
        added_user_id = kwargs.get("user_id")
        added_user = get_object_or_404(CustomUser, user_id=added_user_id)
        try:
            with transaction.atomic():
                if added_user in project.members.all():
                    return JsonResponse({"message": f"{added_user.username}はすでにプロジェクトメンバーです"})
                else:
                    project.save()
                    project.members.add(added_user)
                    return JsonResponse({"message": f"{added_user.username}を追加しました"})
        except Exception as e:
            return JsonResponse({"error": "メンバー追加中にエラーが発生しました。", "details": str(e)}, status=500)

add_member = AddMemberView.as_view()


class AddSearchPaperView(ListView):
    model = Paper
    template_name = "research_projects/add_search_paper.html"
    context_object_name = "papers"
    paginate_by = 20

    def get_queryset(self):
        form = SearchPaperForm(self.request.GET)

        if form.is_valid():
            query = form.cleaned_data.get("query")
            if query:
                queryset = Paper.objects.all()
                queryset = queryset.filter(Q(title__icontains=query) | Q(arxiv__icontains=query) | Q(doi__icontains=query))
            else:
                queryset = Paper.objects.all()

        else:
            queryset = Paper.objects.all()
        
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = SearchPaperForm(self.request.GET)
        context["project_id"] = self.kwargs.get("project_id")
        #ページネーションのために使う
        context['numbers'] = [1, 2, 3, 4]
        return context

add_search_paper = AddSearchPaperView.as_view()


class AddPostView(CreateView):
    model = Post
    template_name = "research_projects/add_post.html"
    context_object_name = "papers"
    fields = ["content"]

    def get_project(self):
        project_id = self.kwargs.get("project_id")
        return get_object_or_404(Project, project_id=project_id)

    def get_success_url(self):
        project = self.get_project()
        return reverse_lazy('research_projects:project_detail', kwargs={"project_id": project.project_id})

    def form_valid(self, form):
        post = form.save(commit=False)
        post.contributer = self.request.user
        post.project = self.get_project()
        post.save()
        return super().form_valid(form)
    
add_post = AddPostView.as_view()


class AddPaperView(View):
    def post(self, request, *args, **kwargs):
        paper_id = kwargs.get("paper_id")
        paper = get_object_or_404(Paper, paper_id=paper_id)
        project_id = kwargs.get("project_id")
        project = get_object_or_404(Project, project_id=project_id)
        try:
            with transaction.atomic():
                i = PapersIndices.objects.filter(project=project).aggregate(Max("index"))["index__max"]
                if i is None:
                    i = 1
                else:
                    i = i + 1
            paper_index , created = PapersIndices.objects.get_or_create(project=project, paper=paper, index=i)
            if created:
                paper_index.save()
                return JsonResponse({"message": f"{paper.title}を追加しました"})
            else:
                return JsonResponse({"message": "追加に失敗"})
        
        except Exception as e:
            # エラーハンドリング
            return JsonResponse({"error": "追加処理中にエラーが発生しました。", "details": str(e)}, status=500)

add_paper = AddPaperView.as_view()
            

class EditCitationView(UpdateView):
    model = PapersIndices
    fields = ["description"]
    template_name = "research_projects/edit_citation.html"

    def get_project(self):
        project_id = self.kwargs.get("project_id")
        project = get_object_or_404(Project, project_id=project_id)
        return project

    def get_object(self):
        project = self.get_project()
        index = self.kwargs.get("index")
        paper_index = get_object_or_404(PapersIndices, project=project, index=index)
        return paper_index
    
    def get_success_url(self):
        project = self.get_project()
        return reverse_lazy('research_projects:project_detail', kwargs={"project_id": project.project_id})
    
edit_citation = EditCitationView.as_view()


class ProjectListView(ListView):
    template_name = "research_projects/project_list.html"
    context_object_name = "projects"
    paginate_by = 20

    def get_queryset(self):
        form = SearchProjectForm(self.request.GET)
        queryset = Project.objects.filter(is_public=True).order_by("-updated_at")
        if "query" in self.request.GET:
            if form.is_valid():
                query = form.cleaned_data.get("query")
                if query:
                    queryset = Project.objects.filter(is_public=True)
                    queryset = queryset.filter(name__icontains=query) | queryset.filter(description__icontains=query) | queryset.filter(short_project_id__icontains=query) | queryset.filter(project_id__icontains=query)
        else:
            if self.request.user.is_authenticated:
                queryset = Project.objects.filter(is_public=True, bookmark_user=self.request.user)
            else:
                queryset = Project.objects.none()
        
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #ページネーションのために使う
        context['numbers'] = [1, 2, 3, 4]  # 配列をコンテキストに追加

        context["form"] = SearchProjectForm(self.request.GET or None)
        if "query" in self.request.GET:
            query = self.request.GET.get("query", "").strip()
            if query:
                context["message"] = f"検索結果： {query}"
            else:
                context["message"] = "全ての結果" 
        else:
            context["message"] = "ブックマークされたプロジェクト"
        return context

project_list = ProjectListView.as_view()


class PublicSwitchView(View):
    def post(self, request, *args, **kwargs):
        project = get_object_or_404(Project, project_id=kwargs.get("project_id"))
        
        if request.POST.get("toggle_public") == "on":
            project.is_public = True
            project.save()
            return JsonResponse({"message": "プロジェクトを公開に切り替えました"})
        
        elif request.POST.get("toggle_public") == None:
            project.is_public = False
            project.save()
            return JsonResponse({"message": "プロジェクトを非公開に切り替えました"})
        
        else:
            return JsonResponse({"message": "無効なリクエストです"})

templates/research_projects/add_member.html
{% extends "base.html" %}
{% load static %}


{# -- タイトル -- #}
{% block title%}論文追加{% endblock %}
{% block extra_css %}<link href="{% static 'css/select2.min.css' %}" rel="stylesheet" />
{% endblock %}

{% block extra_js %}<script src="{% static 'js/select2.min.js' %}"></script>
{%endblock %}



{# --メインコンテンツ --#}
{% block main %}
    <main>
        {{ user }}
        
        <form method="post">
            <section id="add_member_form" class="container mb-4">
                {% csrf_token %}
                {{ form.as_p }}
            </section>
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Create</button>
                <a href="{% url 'accounts:index' %}" class="btn btn-secondary">Back</a>
            </div>
        </form>
    </main>
{% endblock %}

{# -- フッターは表示しない -- #}
{% block footer %}
{% endblock %}

templates/research_projects/add_paper.html
{% extends "base.html" %}
{% load static %}


{# -- タイトル -- #}
{% block title%}論文追加{% endblock %}
{% block extra_css %}<link href="{% static 'css/select2.min.css' %}" rel="stylesheet" />
{% endblock %}

{% block extra_js %}<script src="{% static 'js/select2.min.js' %}"></script>
{%endblock %}



{# --メインコンテンツ --#}
{% block main %}
    <main>
        {{ user }}
        <div>
            <a href="{% url 'papers:import_paper' %}">論文が見つからないとき</a>
        </div>
        
        <form method="post">
            <section id="create_project_form" class="container mb-4">
                {% csrf_token %}
  
                {{ form.as_p }}
            </section>
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Create</button>
                <a href="{% url 'accounts:index' %}" class="btn btn-secondary">Back</a>
            </div>
        </form>
    </main>
{% endblock %}

templates/research_projects/add_post.html
{% extends "base.html" %}
{% load static %}

{# -- タイトル -- #}
{% block title%}ログイン{% endblock %}

{# -- CSS -- #}
{% block extra_css %}
    <style type="text/css">
        main > section > .mx-auto {
            max-width: 400px;
        }
    </style>
{% endblock %}

{# --メインコンテンツ --#}
{% block main %}
    <main>
        {{ user }}
        <form method="post">
            <section id="add_post_form" class="container mb-4">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {% for field in form %}
                {{ field.label }}
                {{ field }}
                {{ field.errors }}
                <br>
                {% endfor %}
            </section>
            <div class="mt-3">
                <button type="submit" class="btn btn-primary">Create</button>
                <a href="{% url 'accounts:index' %}" class="btn btn-secondary">Back</a>
            </div>
        </form>
    </main>
{% endblock %}

templates/research_projects/add_search_member.html
{% extends "base.html" %}
{% load static %}


{# -- タイトル -- #}
{% block title%}文献検索{% endblock %}

{# -- CSS -- #}
{% block extra_css %}
    <link href={% static 'css/research_projects/project_list.css' %} rel="stylesheet" media="all">
{% endblock %}

{# --メインコンテンツ --#}
{% block main %}
    <div class="titleb"><h2>共同研究者一覧</h2>
    </div>
    <div id="search">
        <form method="GET" action="{% url "research_projects:add_search_member" project_id=project_id %}">
            <p class="query">
            {{ form.query }}
            </p>
            <button type="submit">検索</button>
        </form>
    </div>


    <div id="project_list">
        {% if collaborators %}
        {% for collaborator in collaborators %}
        <div class="collaborator">
            <a href="{% url 'accounts:profile' profile_username=collaborator.username %}">{{ collaborator.username }}</a>
            <form method="post" action="{% url "research_projects:add_member" project_id=project_id user_id=collaborator.user_id %}">
                {% csrf_token %}
                <button type="submit">追加</button>
            </form>
        </div>
        {% endfor %}
        {% else %}
        <div class="collaborator">
            共同研究者がいません
        </div>
        {% endif %}

        <div id="pagination">
            {% if page_obj.paginator.num_pages < 10 %}

            {% for i in page_obj.paginator.page_range %}
            <div class="page_num">
                {% if i == page_obj.number %}
                <span class="current_page">{{ i }}</span>
                {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            </div>
            {% endfor %}

            {% elif page_obj.number < 4 %}
            {% for i in numbers %}
            <div class="page_num">
                {% if page_obj.number == i %}
                <span class="current_page">{{ i }}</span>
                {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            </div>
            {% endfor %}
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages|add:"-1" }}">{{ page_obj.paginator.num_pages|add:"-1" }}</a></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></div>
            
            {% elif page_obj.number > page_obj.paginator.num_pages|add:"-3" %}
            <div class="page_num"><a href="?page=1">1</a></div>
            <div class="page_num"><a href="?page=2">2</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            {% for i in numbers %}
            <div class="page_num">
                {% with page_obj.paginator.num_pages|add:-5|add:i as calculated_page %}
                {% if calculated_page == page_obj.number %}
                <span class="current_page">{{ page_obj.paginator.num_pages|add:-5 |add:i }}</span>
                {% else %}
                <a href="?page={{ page_obj.paginator.num_pages|add:-5 |add:i }}">{{ page_obj.paginator.num_pages|add:"-5" |add:i }}</a>
                {% endif %}
                {% endwith %}
            </div>
            {% endfor %}

            {% else %}
            <div class="page_num"><a href="?page=1">1</a></div>
            <div class="page_num"><a href="?page=2">2</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></div>
            <div class="page_num"><span class="current_page">{{ page_obj.number }}</span></div>
            <div class="page_num"><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages|add:"-1" }}">{{ page_obj.paginator.num_pages|add:"-1" }}</a></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages}}">{{ page_obj.paginator.num_pages }}</a></div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/research_projects/add_search_paper.html
{% extends "base.html" %}
{% load static %}


{# -- タイトル -- #}
{% block title%}文献検索{% endblock %}

{# -- CSS -- #}
{% block extra_css %}
    <link href={% static 'css/research_projects/project_list.css' %} rel="stylesheet" media="all">
{% endblock %}

{# --メインコンテンツ --#}
{% block main %}
    <div class="titleb"><h2>文献一覧</h2>
    </div>
    <div id="search">
        <form method="GET" action="{% url "research_projects:add_search_paper" project_id=project_id %}">
            <p class="query">
            {{ form.query }}
            </p>
            <button type="submit">検索</button>
        </form>
    </div>


    <div id="project_list">
        {% if papers %}
        {% for paper in papers %}
        <div class="paper">
            <a href="{% url 'research_projects:add_paper' project_id=project_id paper_id=paper.paper_id %}">{{ paper.title }}</a>
            <form method="post" action="{% url "research_projects:add_paper" project_id=project_id paper_id=paper.paper_id %}">
                {% csrf_token %}
                <button type="submit">追加</button>
            </form>
        </div>
        {% endfor %}
        {% else %}
        <div class="paper">
            文献がありません
        </div>
        {% endif %}

        <div id="pagination">
            {% if page_obj.paginator.num_pages < 10 %}

            {% for i in page_obj.paginator.page_range %}
            <div class="page_num">
                {% if i == page_obj.number %}
                <span class="current_page">{{ i }}</span>
                {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            </div>
            {% endfor %}

            {% elif page_obj.number < 4 %}
            {% for i in numbers %}
            <div class="page_num">
                {% if page_obj.number == i %}
                <span class="current_page">{{ i }}</span>
                {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            </div>
            {% endfor %}
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages|add:"-1" }}">{{ page_obj.paginator.num_pages|add:"-1" }}</a></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></div>
            
            {% elif page_obj.number > page_obj.paginator.num_pages|add:"-3" %}
            <div class="page_num"><a href="?page=1">1</a></div>
            <div class="page_num"><a href="?page=2">2</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            {% for i in numbers %}
            <div class="page_num">
                {% with page_obj.paginator.num_pages|add:-5|add:i as calculated_page %}
                {% if calculated_page == page_obj.number %}
                <span class="current_page">{{ page_obj.paginator.num_pages|add:-5 |add:i }}</span>
                {% else %}
                <a href="?page={{ page_obj.paginator.num_pages|add:-5 |add:i }}">{{ page_obj.paginator.num_pages|add:"-5" |add:i }}</a>
                {% endif %}
                {% endwith %}
            </div>
            {% endfor %}

            {% else %}
            <div class="page_num"><a href="?page=1">1</a></div>
            <div class="page_num"><a href="?page=2">2</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></div>
            <div class="page_num"><span class="current_page">{{ page_obj.number }}</span></div>
            <div class="page_num"><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><span class="dum">・</span></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages|add:"-1" }}">{{ page_obj.paginator.num_pages|add:"-1" }}</a></div>
            <div class="page_num"><a href="?page={{ page_obj.paginator.num_pages}}">{{ page_obj.paginator.num_pages }}</a></div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/research_projects/project_detail.html
{% extends "base.html" %}
{% load static %}

{# -- タイトル -- #}
{% block title %}Project Detail: {{ project.name }}{% endblock %}

{# -- CSS -- #}
{% block extra_css %}
    <link href={% static 'css/research_projects/project_detail.css' %} rel="stylesheet" media="all">
{% endblock %}

{# --メインコンテンツ --#}
{% block main %}
    <div class="titleb">
        <h2>
        {{ project.name }}
        </h2>
    </div>

    <div id="project_detail">

    {% if project.project_url %}
    <div class="project_section" id="project_url">
        <h2>プロジェクトURL</h2>
        <a href="{{ project.project_url }}">{{ project.project_url }}</a>
    </div>
    {% endif %}

    <div class="project_section" id="abstract">
        <h2>概要</h2>
        {% if request.user in project.members.all %}
        <a href="{% url 'research_projects:change_description' project_id=project.project_id %}">変更</a><br>
        {% endif %}
        {% if project.description %}
        {{ project.description }}
        {% else %}
        概要はまだありません
        {% endif %}
    </div>

    {% if request.user in project.members.all %}
    <div id="settings">
        <form method="post" action="{% url 'research_projects:public_switch' project_id=project.project_id %}">
            {% csrf_token %}
            <input class="toggle" type="checkbox" name="toggle_public" {% if project.is_public %} checked="checked" {% endif %}>公開</input>
            <input type="submit" value="設定変更"></input>
        </form>
        <form method="post" action="{% url 'research_projects:visible_switch' project_id=project.project_id %}">
            {% csrf_token %}
            <input class="toggle" type="checkbox" name="toggle_visible" {% if project.is_visible %} checked="checked" {% endif %}>可視</input>
            <input type="submit" value="設定変更"></input>
        </form>
        <a href="{% url 'research_projects:change_url' project_id=project.project_id %}">URL変更</a>
        <a href="{% url 'research_projects:delete_project' project_id=project.project_id %}">プロジェクト削除</a>
    </div>
    {% endif %}
    
    <div id="members">
        <h2>参加メンバー</h2>
    {% for member in members_short_list %}
    <a href="{% url 'accounts:profile' member.username %}"> {{ member.username }}  ID:{{ member.short_user_id }} </a><br>
    {% endfor %}

    {% if request.user in project.members.all %}
    <a href="{% url 'research_projects:add_search_member' project_id=project.project_id %}">メンバー追加</a><br>
    {% endif %}
    </div>

    <div id="posts">
        <h2>投稿</h2>
    {% if request.user in project.members.all %}
    <a href="{% url 'research_projects:create_post' project.project_id %}">Add post</a><br>
    {% endif %}
    <a href="{% url 'research_projects:post_list' project.project_id %}">Post一覧</a><br>
    {% if project.posts.all %}
    {% for post in posts_short_list %}
    {{ post.contributer }}
    {{ post.content }}
    {{ post.posted_on }}
    <br>
    {% endfor %}
    {% else %}
    <p>投稿はまだありません</p>
    {% endif %}
    </div>

    <div id="references">
    <h2>References</h2>
    {% if request.user in project.members.all %}
    <a href="{% url 'research_projects:add_search_paper' project_id=project.project_id %}">Add paper</a><br>
    {% endif %}
    {% for paper_index in project.papers_indices.all %}

    {{ paper_index.index }} {{ paper_index.paper.title }} {% for author in paper_index.paper.authors.all %} {{ author.first_name }} {{author.last_name}} {% endfor %} {{ paper_index.paper.arxiv }} {% if paper_index.description %} {{ paper_index.description }} {% endif %}
    <br>
    {% if request.user in project.members.all %}
    <p><a href="{% url 'research_projects:edit_citation' project.project_id paper_index.index %}">Edit</a></p>
    {% endif %}
    {% endfor %}
    </div>
</div>
{% endblock %}