accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('user/<str:profile_username>/', views.profile, name="profile"),
    path('collaboration/request/<uuid:to_user_id>/', views.send_collaboration_request, name="send_collaboration_request"),
    path('collaboration/respond/<uuid:request_id>/<str:response>', views.manage_collaboration_request, name="manage_collaboration_request"),
    path('collaboration/withdraw/<uuid:request_id>/', views.withdraw_collaboration_request, name="withdraw_collaboration_request"),
    path('user_search', views.user_search, name="user_search"),
    path('collaboration/list/<str:username>', views.collaboration_request_list, name="collaboration_request_list"),
    path('collaborator_list/', views.collaborator_list, name="collaborator_list"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import TemplateView
# from accounts import views as accounts_views
# from papers import views as papers_views
# from research_projects import views as research_project_views
#from . import views

class TopPageView(TemplateView):
    template_name = "index.html"

top_page = TopPageView.as_view()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', top_page, name="top_page"),
    path('accounts/', include('accounts.urls')),
    path('papers/', include('papers.urls')),
    path('research_projects/', include('research_projects.urls'))
    
]

papers/urls.py
from django.urls import path

from . import views

app_name = "papers"

urlpatterns = [
    path('import_paper', views.import_paper, name="import_paper"),
    path('paper_list', views.paper_list, name="paper_list"),
    path('paper_detail/<uuid:paper_id>', views.paper_detail, name="paper_detail"),
#    path('detail/<uuid:pk>', views.project_detail, name="project_detail"),
#    path('add_post/<uuid:project_id>', views.create_post, name="create_post")
]

research_projects/urls.py
from django.urls import path

from . import views

app_name = "research_projects"

urlpatterns = [
    path('create_project/', views.create_project, name="create_project"),
    path('detail/<uuid:project_id>/', views.project_detail, name="project_detail"),
    path('add_post/<uuid:project_id>/', views.add_post, name="create_post"),
    path('add_search_paper/<uuid:project_id>/', views.add_search_paper, name="add_search_paper"),
    path('add_paper/<uuid:project_id>/<uuid:paper_id>/', views.add_paper, name="add_paper"),
    path('edit_citation/<uuid:project_id>/<int:index>/', views.edit_citation, name="edit_citation"),
    path('project_list/', views.project_list, name="project_list"),
    path('add_search_member/<uuid:project_id>/', views.add_search_member, name="add_search_member"),
    path('add_member/<uuid:project_id>/<uuid:user_id>/', views.add_member, name="add_member"),
    path('public_switch/<uuid:project_id>/', views.public_switch, name="public_switch"),
    path('visible_switch/<uuid:project_id>/', views.visible_switch, name="visible_switch"),
    path('change_url/<uuid:project_id>/', views.change_url, name="change_url"),
    path('change_description/<uuid:project_id>/', views.change_description, name="change_description"),
    path('delete_project/<uuid:project_id>/', views.delete_project, name="delete_project"),
    path('post_list/<uuid:project_id>/', views.post_list, name="post_list"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>    
<html lang=ja>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'css/base.css' %}" rel="stylesheet" media="all">
        {% block extra_css %}{% endblock %}
    </head>
    <body>
        {% block top_button %}
        <div id="back_to_top">
            <a href="#" id="top_button"><div id="btp_text">↑</div></a>
        </div>
        {% endblock %}
        
        {% block header %}
        <header>
            <div class="inner">
                <h1><a href="{% url 'top_page' %}">文献・プロジェクト管理</a></h1>
                ヘッダー領域<br>
                <div id="top_right">
                    <div class="button">
                        {% if user.is_authenticated %}
                        <span class="now_login">ログイン中</span>
                        {% else %}
                        <a href="{% url 'accounts:login' %}">ログイン</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </header>

        {% endblock %}
        {% block menu_bar %}
        <nav id="menu_bar">
            <ul class="inner clearfix">
                <li><a href="{% url 'top_page' %}">TOPページ</a></li>
                <li><a href="{% url 'research_projects:project_list' %}">公開プロジェクト一覧</a></li>
                <li><a href="{% url 'papers:paper_list' %}">文献一覧</a></li>
                <li>
                {% if user.is_authenticated %}
                <a href="{% url 'accounts:profile' profile_username=user.username %}">
                {% else %}
                <a href="{% url 'accounts:login' %}">
                {% endif %}
                マイページ</a></li>
            </ul>
        </nav>
        {% endblock %}
            
        <div class="contents">
            {% block side_menu %}
            <nav id="side_menu">
                <ul class="main_menu">
                    <li class="heading"><a href="{% url 'top_page' %}">TOPページ</a></li>
                    <li class="heading"><a href="#l">マイプロジェクト</a></li>
                    {% if user.is_authenticated %}
                        {% for project in latest_projects %}
                        <li class="menu_element"><a href="{% url 'research_projects:project_detail' project_id=project.project_id %}">{{ project.name }}</a></li>
                        {% endfor %}
                    {% endif %}
                    <li class="heading"><a href="{% url 'accounts:collaborator_list' %}">共同研究者一覧</li>
                    <li class="heading"><a href="{% url 'research_projects:project_list' %}">公開プロジェクト一覧</a></li>
                    <li class="heading"><a href="{% url 'accounts:user_search' %}">ユーザー検索</a></li>
                    <li class="heading"><a href="{% url 'papers:paper_list' %}">文献一覧</a></li>
                    <li class="heading">
                        {% if user.is_authenticated %}
                        <a href="{% url 'accounts:profile' profile_username=user.username %}">
                        {% else %}    
                        <a href="{% url 'accounts:login' %}">
                        {% endif %}
                        マイページ</a></li>
                </ul>
            </nav>
            {% endblock %}
            <div id="main">
                {% block main %}
                メイン文
                {% endblock %}
            </div>
        </div>
        {% block footer %}
        <footer>
            <div class="inner">
                フッター領域
            </div>
        </footer>
        {% endblock %}
        {% block information%}
        <div id="information" class="inner">
            info
        </div>
        {% endblock %}

    </body>
</html>     

templates/index.html
{% extends "base.html" %}
{% load static %}

{# -- タイトル -- #}
{% block title%}トップページ：文献・プロジェクト管理{% endblock %}


{# --メインコンテンツ --#}
{% block main %}
    <div id="log">
        <div class="titlef">ご案内</div>
        <div class="text">現在は更新の時にデータが消える場合があります。作り直すか、taiichiac@gmail.comにご連絡をお願いします。また、一部JSONレスポンスをそのままにしている部分などあるので、ブラウザの戻るボタンを使ってください。</div>
    </div>
{% endblock %}